trigger:
  branches:
    include:
    - main
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: Docker@2
    displayName: buildAndPush
    inputs:
      containerRegistry: fc85f685-a8f7-4ce6-8b2b-016778f7c85e
      repository: authinmern-containerRepo
      buildContext: $(System.DefaultWorkingDirectory)
      tags: >-
        $(Build.BuildId)
        latest
      arguments: 'CACHEBUST=$(date +%s)'
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFiles: junit.xml
...
